extends:
  - airbnb-typescript
parser: '@typescript-eslint/parser'
env:
  browser: true
  node: true
  es6: true
  jest: true
plugins:
  - import
  - react
  - react-hooks
  - '@typescript-eslint'
settings:
  react:
    pragma: "h"
rules:
  linebreak-style: 0
  no-console: 0
  arrow-parens: 0
  implicit-arrow-linebreak: 0
  operator-linebreak: 0
  no-confusing-arrow: 0
  import/no-extraneous-dependencies: 0
  import/no-unresolved: 0
  import/extensions: 0
  jsx-a11y/no-static-element-interactions: 0
  jsx-a11y/anchor-is-valid: 0
  object-curly-newline: 0
  react/jsx-no-duplicate-props: 2
  react/self-closing-comp: 2
  react/prefer-es6-class: 2
  react/no-string-refs: 2
  react/require-render-return: 2
  react/no-find-dom-node: 2
  react/no-is-mounted: 2
  react/jsx-no-comment-textnodes: 2
  react/jsx-curly-spacing: 2
  react/jsx-no-undef: 2
  react/jsx-uses-react: 2
  react/jsx-uses-vars: 2
  react/jsx-filename-extension: 0
  react/jsx-one-expression-per-line: 0
  react/no-unknown-property: 0
  "@typescript-eslint/explicit-function-return-type": 0
  "@typescript-eslint/indent":
    - "error"
    - 2
  "@typescript-eslint/interface-name-prefix": 0
